import { clientEnv } from '@/lib/env'

export const brand = {
  displayName: 'ThoorigAI Infotech',
  legalName: 'ThoorigAI Infotech LLP',
  shortName: 'ThoorigAI',
  tagline: 'Professional Learning & Training',
  logoPath: '/thoorigai-logo.webp',
  invoicePrefix: 'TAI',
  supportEmail: 'support@thoorigai.in',
  websiteUrl: clientEnv.NEXT_PUBLIC_APP_URL,
  verifyBaseUrl: clientEnv.NEXT_PUBLIC_VERIFY_BASE_URL.replace(/\/+$/, ''),
  theme: {
    colors: {
      navy: '#0f172a',
      navySecondary: '#1e293b',
      navyDeep: '#020617',
      accent: '#6366f1',
      accentDeep: '#4f46e5',
      accentLight: '#818cf8',
      primary: '#1d4ed8',
      primaryHover: '#1e40af',
      ink: '#0f172a',
      muted: '#64748b',
      line: '#e2e8f0',
      surface: '#ffffff',
      canvasStart: '#f8fafc',
      canvasEnd: '#e0e7ff',
      green: '#10b981',
      greenBackground: '#ecfdf5',
      red: '#ef4444',
      redBackground: '#fef2f2',
      amber: '#f59e0b',
      amberBackground: '#fffbeb',
    },
  },
} as const

export const brandCssVariables = {
  '--brand-navy': brand.theme.colors.navy,
  '--brand-navy-secondary': brand.theme.colors.navySecondary,
  '--brand-navy-deep': brand.theme.colors.navyDeep,
  '--brand-accent': brand.theme.colors.accent,
  '--brand-accent-deep': brand.theme.colors.accentDeep,
  '--brand-accent-light': brand.theme.colors.accentLight,
  '--brand-primary': brand.theme.colors.primary,
  '--brand-primary-hover': brand.theme.colors.primaryHover,
  '--brand-ink': brand.theme.colors.ink,
  '--brand-muted': brand.theme.colors.muted,
  '--brand-line': brand.theme.colors.line,
  '--brand-surface': brand.theme.colors.surface,
  '--brand-canvas-start': brand.theme.colors.canvasStart,
  '--brand-canvas-end': brand.theme.colors.canvasEnd,
  '--brand-green': brand.theme.colors.green,
  '--brand-green-background': brand.theme.colors.greenBackground,
  '--brand-red': brand.theme.colors.red,
  '--brand-red-background': brand.theme.colors.redBackground,
  '--brand-amber': brand.theme.colors.amber,
  '--brand-amber-background': brand.theme.colors.amberBackground,
} as const
