import type { Course, GstSettings, Payment, Student } from './types'

export const gstSettings: GstSettings = {
  rate: 18,
  gstin: '33AAZFT3654J1ZI',
  enabled: true,
}

export const initialStudents: Student[] = [
  {
    registerId: 1048,
    name: 'Kavya Srinivasan',
    course: 'Professional Course',
    batch: '12 Aug 2026',
    total: 42000,
    paid: 42000,
    phone: '9876543210',
    status: 'Fully Paid',
    gender: 'Female',
    dob: '2001-05-14',
    altPhone: '9876500001',
    maritalStatus: 'Single',
    email: 'kavya.s@example.com',
    country: 'India',
    state: 'Tamil Nadu',
    city: 'Tuticorin',
    area: 'Millerpuram',
    leadType: 'Hot',
    leadSource: 'Walk-in',
    comments: 'Interested in core cloud architecture and full-stack deployment.',
    knowledgeTags: ['Web Dev', 'React', 'Full Stack'],
  },
  {
    registerId: 1047,
    name: 'Arjun Prakash',
    course: 'ThoorigAI Course - Internship',
    batch: '09 Aug 2026',
    total: 36000,
    paid: 18000,
    phone: '9840123456',
    status: 'Pending',
    gender: 'Male',
    dob: '2000-11-22',
    maritalStatus: 'Single',
    email: 'arjun.p@example.com',
    country: 'India',
    state: 'Tamil Nadu',
    city: 'Tirunelveli',
    area: 'Palayamkottai',
    leadType: 'Warm',
    leadSource: 'Social Media',
    comments: 'Looking for hands-on internship with AI focus.',
    knowledgeTags: ['AI/ML', 'Python', 'Internship'],
  },
  {
    registerId: 1046,
    name: 'Meena Lakshmi',
    course: 'Crash Course (1.5 Months)',
    batch: '04 Aug 2026',
    total: 24000,
    paid: 24000,
    phone: '9962012345',
    status: 'Fully Paid',
    gender: 'Female',
    dob: '1999-08-19',
    maritalStatus: 'Married',
    email: 'meena.l@example.com',
    country: 'India',
    state: 'Tamil Nadu',
    city: 'Tuticorin',
    area: 'Cruz Fernandez Puram',
    leadType: 'Hot',
    leadSource: 'Reference',
    comments: 'Referred by alumni. Wants fast track web frontend course.',
    knowledgeTags: ['Frontend', 'UI Design'],
  },
  {
    registerId: 1045,
    name: 'Rohit Kumar',
    course: 'Slash Course (1 Month)',
    batch: '28 Jul 2026',
    total: 18000,
    paid: 9000,
    phone: '9789012345',
    status: 'Pending',
    gender: 'Male',
    dob: '2002-02-10',
    maritalStatus: 'Single',
    email: 'rohit.k@example.com',
    country: 'India',
    state: 'Tamil Nadu',
    city: 'Madurai',
    area: 'KK Nagar',
    leadType: 'Warm',
    leadSource: 'Website',
    comments: 'College student building weekend portfolio projects.',
    knowledgeTags: ['HTML/CSS', 'Beginner'],
  },
  {
    registerId: 1044,
    name: 'Divya Narayanan',
    course: 'Professional Course',
    batch: '20 Jul 2026',
    total: 42000,
    paid: 42000,
    phone: '9884312345',
    status: 'Fully Paid',
    gender: 'Female',
    dob: '2001-09-30',
    maritalStatus: 'Single',
    email: 'divya.n@example.com',
    country: 'India',
    state: 'Tamil Nadu',
    city: 'Tuticorin',
    area: 'Bryant Nagar',
    leadType: 'Hot',
    leadSource: 'Campus Drive',
    comments: 'Selected during campus drive. Excellent programming aptitude.',
    knowledgeTags: ['Java', 'Web Dev'],
  },
]

export const initialPayments: Payment[] = [
  { id: 'RCPT-1086', student: 'Kavya Srinivasan', method: 'UPI', date: '14 Sep 2026', amount: 12000, invoice: 'TAI/2026/INV086', studentId: 1048 },
  { id: 'RCPT-1085', student: 'Arjun Prakash', method: 'Bank Transfer', date: '13 Sep 2026', amount: 18000, invoice: 'TAI/2026/INV085', studentId: 1047 },
  { id: 'RCPT-1084', student: 'Meena Lakshmi', method: 'Cash', date: '11 Sep 2026', amount: 12000, invoice: 'TAI/2026/INV084', studentId: 1046 },
  { id: 'RCPT-1083', student: 'Rohit Kumar', method: 'UPI', date: '09 Sep 2026', amount: 9000, invoice: 'TAI/2026/INV083', studentId: 1045 },
]

export const initialCourses: Course[] = [
  { id: 'CRS-01', name: 'Professional Course', fee: 42000, duration: '6 Months', description: 'Comprehensive industry-aligned software engineering and architecture training.' },
  { id: 'CRS-02', name: 'ThoorigAI Course - Internship', fee: 36000, duration: '3 Months', description: 'Hands-on live client project internship focusing on AI-assisted application design.' },
  { id: 'CRS-03', name: 'Crash Course (1.5 Months)', fee: 24000, duration: '1.5 Months', description: 'Fast-paced intensive program covering modern web development fundamentals.' },
  { id: 'CRS-04', name: 'Slash Course (1 Month)', fee: 18000, duration: '1 Month', description: 'Foundational boot-camp focusing on UI design and frontend fundamentals.' },
  { id: 'CRS-05', name: 'Full Stack Development', fee: 48000, duration: '6 Months', description: 'Complete MERN & Next.js ecosystem training with cloud database deployments.' },
  { id: 'CRS-06', name: 'Data Science & AI', fee: 52000, duration: '6 Months', description: 'Practical machine learning, LLMs, data analytics, and Python frameworks.' },
  { id: 'CRS-07', name: 'UI/UX Design Masterclass', fee: 30000, duration: '2 Months', description: 'Figma to frontend design systems, typography, micro-interactions, and prototyping.' },
]


