import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'
import { createClient } from '@/utils/supabase/server'
import { listPayments } from '@/lib/server-data'
import { paymentSchema } from '@/lib/validation'
import { brand } from '@/lib/brand'
import { generateUniqueVerificationCode } from '@/lib/utils'
import z from 'zod'

export async function GET(req: NextRequest) {
  // Create a Supabase client with the anon key for this request
  const supabase = await createClient()
  const { data: { user }, error: authError } = await supabase.auth.getUser()
  const session = user ? { user } : null
  if (authError || !session) {
    return new NextResponse(JSON.stringify({ error: 'Unauthorized' }), { status: 401 })
  }

  try {
    const { searchParams } = new URL(req.url)
    const pageParam = searchParams.get('page')
    const pageSizeParam = searchParams.get('pageSize')
    const page = pageParam ? parseInt(pageParam, 10) : 1
    const pageSize = pageSizeParam ? parseInt(pageSizeParam, 10) : 50

    const result = await listPayments(supabase, { page, pageSize })
    // Add source for consistency with previous responses
    return NextResponse.json({ ...result, source: 'supabase' })
  } catch (error) {
    return NextResponse.json({ error: error instanceof Error ? error.message : 'Unable to load payments' }, { status: 500 })
  }
}

export async function POST(req: NextRequest) {
  // Create a Supabase client with the anon key for this request
  const supabase = await createClient()
  const { data: { user }, error: authError } = await supabase.auth.getUser()
  const session = user ? { user } : null
  if (authError || !session) {
    return new NextResponse(JSON.stringify({ error: 'Unauthorized' }), { status: 401 })
  }

  try {
    const body = await req.json()
    // Validate the request body with zod schema
    const parsedBody = paymentSchema.parse(body)

    const {
      studentId,
      amount,
      method,
      date,
      transactionId,
      customNote,
      gstRate,
      // Remove id and invoice from destructuring as they will be generated by DB
    } = parsedBody

    // Business-logic validation will be done after fetching the student (checking balance)

    if (!supabase) {
      const { initialStudents, initialPayments } = require('@/lib/mock-data')
      const student = initialStudents.find((s: any) => s.registerId === studentId)
      if (!student) return NextResponse.json({ error: 'Student not found.' }, { status: 404 })
      const balance = Number(student.total) - Number(student.paid)
      if (amount > balance) return NextResponse.json({ error: `Payment exceeds the remaining balance of ${balance}.` }, { status: 400 })

      student.paid = Number(student.paid) + amount
      student.status = student.paid >= Number(student.total) ? 'Fully Paid' : 'Pending'

      const dateStr = new Date(date + 'T00:00:00').toLocaleDateString('en-IN', {
        day: '2-digit',
        month: 'short',
        year: 'numeric',
      })

      const next = Date.now()
      const paymentId = id || `RCPT-${next}`
      const finalInvoice = invoice || `${brand.invoicePrefix}/${new Date().getFullYear()}/INV${String(next).slice(-6)}`

      const newPayment: any = {
        id: paymentId,
        student: student.name,
        method,
        date: dateStr,
        amount,
        invoice: finalInvoice,
        studentId: studentId,
      }
      if (cgst !== undefined && cgst > 0) newPayment.cgst = cgst
      if (sgst !== undefined && sgst > 0) newPayment.sgst = sgst
      if (transactionId !== undefined) newPayment.transactionId = transactionId
      if (customNote !== undefined) newPayment.customNote = customNote
      if (gstRate !== undefined) newPayment.gstRate = gstRate
      initialPayments.unshift(newPayment)

      return NextResponse.json({ data: newPayment, source: 'mock' }, { status: 201 })
    }

    const { data: student, error: studentError } = await supabase
      .from('students')
      .select('*')
      .eq('register_id', studentId)
      .single()
    if (studentError || !student) return NextResponse.json({ error: 'Student not found.' }, { status: 404 })

    const balance = Number(student.total) - Number(student.paid)
    if (amount > balance) {
      return NextResponse.json({ error: `Payment exceeds the remaining balance of ${balance}.` }, { status: 400 })
    }

    const paymentDate = date ?? new Date().toISOString().slice(0, 10)

    const paymentRow: Record<string, unknown> = {
      student_id: student.id,
      student_register_id: studentId,
      method,
      amount,
      payment_date: paymentDate,
      transaction_id: transactionId ?? null,
      custom_note: customNote ?? null,
      gst_rate: gstRate,
      cgst,
      sgst,
    }

    const { data: payment, error: paymentError } = await supabase
      .from('payments')
      .insert(paymentRow)
      .select()
      .single()
    if (paymentError) return NextResponse.json({ error: paymentError.message }, { status: 400 })

    const paid = Number(student.paid) + amount
    const { error: updateError } = await supabase
      .from('students')
      .update({ paid, status: paid >= Number(student.total) ? 'Fully Paid' : 'Pending', updated_at: new Date().toISOString() })
      .eq('id', student.id)
    if (updateError) return NextResponse.json({ error: updateError.message }, { status: 400 })

    const dateStr = new Date(paymentDate + 'T00:00:00').toLocaleDateString('en-IN', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
    })

    // Create verifiable document entry for this invoice (only in real Supabase mode)
    if (supabase) {
      try {
        const verificationCode = await generateUniqueVerificationCode(supabase);
        await supabase
          .from('verifiable_documents')
          .insert({
            doc_type: 'invoice',
            reference_id: payment.id, // Using payment ID as reference for invoice
            verification_code: verificationCode,
            status: 'active'
          });
      } catch (verisonError) {
        // Log the error but don't fail the payment creation
        console.error('Failed to create verifiable document entry for invoice:', verisonError);
      }
    }

    return NextResponse.json(
      {
        data: {
          id: payment.id,
          student: student.name,
          method,
          date: dateStr,
          amount: Number(payment.amount),
          invoice: payment.invoice,
          studentId: studentId,
          studentRowId: student.id,
          cgst: Number(payment.cgst) ?? 0,
          sgst: Number(payment.sgst) ?? 0,
          transactionId: payment.transaction_id,
          customNote: payment.custom_note,
          gstRate: Number(payment.gst_rate) ?? 0,
        },
        source: 'supabase',
      },
      { status: 201 }
    )
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json({ error: error.errors }, { status: 400 })
    }
    return NextResponse.json({ error: error instanceof Error ? error.message : 'Unable to record payment' }, { status: 500 })
  }
}
